main_app/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('art/', views.art_index, name='art_index'),
    path('art/create', views.ArtCreate.as_view(), name='art_create'),
    path('art/<int:art_id>/', views.art_detail, name='art_detail'),
    path('art/<int:art_id>/add_photo/', views.add_photo, name='add_photo'),
    path('art/<int:art_id>/delete_photo/<int:photo_id>', views.delete_photo, name='delete_photo'),
    path('art/<int:art_id>/add_comment/', views.add_comment, name='add_comment'),
    path('art/<int:pk>/owner_update/', views.ArtOwnerUpdate.as_view(), name='art_owner_update'),
    path('art/<int:pk>/update/', views.ArtUpdate.as_view(), name='art_update'),    
    path('art/<int:pk>/delete/', views.ArtDelete.as_view(), name='art_delete'),
    path('art/comment/<int:pk>/delete/', views.commentDelete.as_view(), name='comment_delete'),
    path('accounts/signup/', views.signup, name='signup'),
    path('profile/detail/', views.profile_detail, name='profile_detail'),
    path('profile/update/', views.update_profile, name='update_profile'),
    path('profile/detail/add_photo/', views.add_profile_photo, name='add_profile_photo'),
    path('profile/detail/delete_photo/', views.delete_profile_photo, name='delete_profile_photo')
]

start/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
  path('admin/', admin.site.urls),
  path('', include('main_app.urls')),
  path('accounts/', include('django.contrib.auth.urls')),
]

main_app/models.py
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db import models
from django.db.models.signals import post_save
from django.urls import reverse
import datetime
from phonenumber_field.modelfields import PhoneNumberField

PRESENT = (
    ('Yes', 'Yes'),
    ('At Risk', 'At Risk'),
    ('No', 'No')
)

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = PhoneNumberField()

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()

class ProfilePhoto(models.Model):
    url = models.CharField(max_length=200)
    filename = models.CharField(max_length=50)
    profile = models.OneToOneField(Profile, on_delete=models.CASCADE)

class Art(models.Model):
    name = models.CharField(max_length=100)
    artist = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    present = models.CharField(
        max_length=7,
        choices=PRESENT,
        default=PRESENT[0][0]
    )

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('art_detail', kwargs={'art_id': self.id})

class Photo(models.Model):
    url = models.CharField(max_length=200)
    filename = models.CharField(max_length=50)
    art = models.ForeignKey(Art, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

class Comment(models.Model):
    date = models.DateField(default=datetime.datetime.now)
    content = models.TextField(max_length=200)
    art = models.ForeignKey(Art, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    # change the default sort for comments
    class Meta:
        ordering = ['-date']

main_app/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm
from .models import Comment, Profile

class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'password1', 'password2']

class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = ['phone']

class CommentForm(ModelForm):
  class Meta:
    model = Comment
    fields = ['content']

main_app/views.py
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from .models import Art, Photo, Comment, ProfilePhoto
from .forms import CommentForm, ProfileForm, SignUpForm

import uuid  # for generating random strings (what we name our photos)
import boto3  # sdk to interact with aws bucket

# Add these "constants" below the imports
S3_BASE_URL = 'https://s3-us-east-2.amazonaws.com/'
BUCKET = 'start-streetart'

class ArtCreate(LoginRequiredMixin, CreateView):
    model = Art
    fields = ['name', 'artist', 'description']

    # When valid art is added, assign a user as its owner.
    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class commentDelete(DeleteView):
    model = Comment
    success_url = '/'

class ArtDelete(DeleteView):
    model = Art
    success_url = '/art/'

class ArtOwnerUpdate(UpdateView):
    model = Art
    fields = ['description', 'artist', 'name', 'present']
    success_url = '/art/'

class ArtUpdate(UpdateView):
    model = Art
    fields = ['present']
    success_url = '/art/'

def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

@login_required
def art_index(request):
    art = Art.objects.all()
    return render(request, 'art/index.html', {'art': art})

@login_required
def art_detail(request, art_id):
    oneArt = Art.objects.get(id=art_id)
    comment_form = CommentForm()
    return render(request, 'art/detail.html', {
        'oneArt': oneArt,
        'comment_form': comment_form,
        'user': request.user
    })

@login_required
def add_photo(request, art_id):
    # photo-file will be the "name" attribute on the <input type="file">
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')
        # need a unique "key" for S3 / needs image file extension too
        key = uuid.uuid4().hex[:6] + \
            photo_file.name[photo_file.name.rfind('.'):]
        try:
            s3.upload_fileobj(photo_file, BUCKET, key)
            # build the full url string
            url = f"{S3_BASE_URL}{BUCKET}/{key}"
            user = request.user
            photo = Photo(url=url, art_id=art_id, filename=key, user=user)
            photo.save()
        except:
            print('An error occurred uploading file to S3')
    return redirect('art_detail', art_id=art_id)

def delete_photo(request, art_id, photo_id):
    dbPhoto = Photo.objects.get(id=photo_id)
    s3 = boto3.resource('s3')
    photo = s3.Object('start-streetart', dbPhoto.filename)
    photo.delete()
    dbPhoto.delete()
    return redirect('art_detail', art_id=art_id)

@login_required
def add_comment(request, art_id):
    form = CommentForm(request.POST)
    if form.is_valid():
        new_comment = form.save(commit=False)
        new_comment.art_id = art_id
        new_comment.user_id = request.user.id
        new_comment.save()
    return redirect('art_detail', art_id=art_id)

def signup(request):
    error_message = ''
    if request.method == 'POST':
        sign_up_form = SignUpForm(request.POST)
        if sign_up_form.is_valid():
            user = sign_up_form.save()
            # Profile.objects.create()
            login(request, user)
            return redirect('art_index')
        else:
            error_message = 'Invalid sign up - try again'
    # A bad POST or a GET request, so render signup.html with an empty form
    sign_up_form = SignUpForm()
    context = {'sign_up_form': sign_up_form, 'error_message': error_message}
    return render(request, 'registration/signup.html', context)

@login_required
def profile_detail(request):
    profile_form = ProfileForm(instance=request.user)
    return render(request, 'profile/detail.html', {
        'user': request.user,
        'profile_form': profile_form
    })

@login_required
def update_profile(request):
    user = request.user
    if request.method == 'POST':
        profile_form = ProfileForm(request.POST, instance=request.user.profile)
        if profile_form.is_valid():
            profile_form.save()
            return redirect('profile_detail')
        else:
            messages.error(request, _('Please correct the error below.'))
    else:
        profile_form = ProfileForm(instance=request.user.profile)
    return render(request, 'profile/detail.html', {
        'user': user,
        'profile_form': profile_form
    })

@login_required
def add_profile_photo(request):
    # photo-file will be the "name" attribute on the <input type="file">
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')
        # need a unique "key" for S3 / needs image file extension too
        key = uuid.uuid4().hex[:6] + \
            photo_file.name[photo_file.name.rfind('.'):]
        # just in case something goes wrong
        try:
            s3.upload_fileobj(photo_file, BUCKET, key)
            # build the full url string
            url = f"{S3_BASE_URL}{BUCKET}/{key}"
            filename = key
            profile = request.user.profile
            # we can assign to art_id or at (if you have an art object)
            photo = ProfilePhoto(url=url, filename=filename, profile=profile)
            photo.save()
        except:
            print('An error occurred uploading file to S3')
    return redirect('profile_detail')

@login_required
def delete_profile_photo(request):
    existing_profile_photo = request.user.profile.profilephoto
    s3del = boto3.resource('s3')
    photo = s3del.Object(BUCKET, existing_profile_photo.filename)
    photo.delete()
    existing_profile_photo.delete()
    return redirect('profile_detail')

main_app/templates/art/detail.html
{% extends 'base.html' %} 
{% block content %}
<!-- <h1>Art Details</h1> -->
<div class="container">
  <div class="card-content">
    {% for photo in oneArt.photo_set.all %}
      <img id="img-details" class="responsive-img card-panel" src="{{photo.url}}" />
      <!-- if the user uploaded the photo or the user created the art page they can delete the photo, but no other users can. -->
      {% if user == photo.user or user == art.user %}
        <a class="btn waves-effect waves-light pink lighten-2" href="{% url 'delete_photo' oneArt.id photo.id %}" value="delete">Delete Photo<i class="material-icons left">delete_forever</i></a>
      {% endif %}
      {% empty %}
        <div class="card-content">
          <div class="card-panel teal-text center-align">No Photos Uploaded</div>
        </div>
      {% endfor %}
      <div class="col s12 l6">
        <form
          action="{% url 'add_photo' oneArt.id %}"
          enctype="multipart/form-data"
          method="POST"
          class="card-panel"
        >
          {% csrf_token %}
          <input type="file" name="photo-file" />
          <br /><br />
          <button class="btn waves-effect waves-light blue" type="submit" value="Upload Photo" name="action">Upload Photo
              <i class="material-icons left">add_a_photo</i>
        </form>
      </div>
      <ul class="collection">
        <li class="collection-header">{{ oneArt.name }}</li>
        <li class="collection-item">Artist: {{ oneArt.artist }}</li>
        <li class="collection-item">Description: {{ oneArt.description }}</li>
        <li class="collection-item">Added by: {{oneArt.user.first_name}} {{oneArt.user.last_name}}</li>
        <li class="collection-item">Art is still present: {{oneArt.present}}</li>
      </ul>
      <!-- If user viewing the page started the page, give them ability to delete it along with fully edit the art details. If not let them edit a limited set of art details. -->
      {% if user == oneArt.user %}
        <a class="btn waves-effect waves-light cyan lighten-1" href="{% url 'art_owner_update' oneArt.id %}" value="Edit">Edit<i class="material-icons left">edit</i></a>
        <a class="btn waves-effect waves-light pink lighten-2" href="{% url 'art_delete' oneArt.id %}" value="delete">Delete Art<i class="material-icons left">delete_forever</i></a>
      {% else %}
        <a class="btn waves-effect waves-light cyan lighten-1" href="{% url 'art_update' oneArt.id %}" value="Edit">Edit<i class="material-icons left">edit</i></a>
      {% endif %}
<!-- Comments Form -->
      <div class="col s12 l6">
        <form action="{% url 'add_comment' oneArt.id %}" method="post">
          {% csrf_token %}
          {{ comment_form.as_p }}
          <button class="btn waves-effect waves-light cyan lighten-1" type="submit" value="Add Comment" name="action">Add Comment
            <i class="material-icons left">add_circle</i>
          </button>
        </form> 
      </div>
  </div>
</div>
<!-- Comments -->
{% if oneArt.comment_set.all %}
<div class="container">
  <table class="striped">
    <thead>
      <tr><th>Profile Photo</th><th>User</th><th>Comment</th><th>Date</th><th>Delete</th></tr>
    </thead>
    <tbody>
      {% for comment in oneArt.comment_set.all %}
        <tr>
          <td>
            {% if comment.user.profile.profilephoto %}
              <img style="object-fit: cover; height: 60px; width: 60px;" class="circle" src="{{comment.user.profile.profilephoto.url}}" />
            {% else %}
              <img style="object-fit: cover; height: 60px; width: 60px;" class="circle" src="/static/main_app/images/defaultProfile.png" />
            {% endif %}
          </td>
          <td>{{comment.user.first_name}} {{comment.user.last_name}}</td>
          <td>{{comment.content}}</td>
          <td>{{comment.date}}</td>
          {% if user == comment.user %}
            <td><a class="btn waves-effect waves-light pink lighten-2" href="{% url 'comment_delete' comment.id %}"><i class="material-icons">delete_forever</i></a></td>
          {% else%}
            <td></td>
          {% endif %}
        </tr>
        {% endfor %}
      </tbody>
    </table>
</div>
{% endif %}
{% endblock %}

            

main_app/templates/art/index.html
{% extends 'base.html' %} 
{%block h1%} <h3>All Arts List</h3>{%endblock h1%}
{% block content %}
{% for oneArt in art %}
<!-- <div class="flex-container"> -->
<div class="card">
  <div class="card-image">
    {% if oneArt.photo_set.all.first %}
      <img id="img-height" class="responsive-img" src="{{oneArt.photo_set.all.first.url}}" />
    {% else %}
      <div class="card-panel blue-text center-align">No Photos Uploaded</div>
    {% endif%}
    </div>
      <div class="card-content">
        <span class="blue-text text-darken-2 card-title">{{ oneArt.name }}</span>
        <p>{{ oneArt.description }}</p>
      </div>
      <div class="card-action">
        <a class="btn waves-effect waves-light cyan lighten-1" href="{% url 'art_detail' oneArt.id %}">Details</a>
      </div>
  </div>
</div>
{% endfor %}
{% endblock %}